version: '3'
services:
  vue:
    container_name: vue
    build:
      context: ./webapp
      dockerfile: Dockerfile
    volumes:
      - ./webapp:/app
      - /webapp/node_modules
    ports:
      - 8080:80
    depends_on:
      - flask

  flask:
    container_name: flask
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 5001:5001
  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #     - ./certs:/etc/nginx/certs
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - flask