version: '3'
services:
  vue:
    container_name: vue
    build:
      context: ./webapp
      dockerfile: Dockerfile
    volumes:
      - ./webapp:/app
      - /webapp/node_modules
    ports:
      - 8080:80
    depends_on:
      - flask
    restart: unless-stopped

  flask:
    container_name: flask
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    expose:
      - "5001"
      
  nginx_proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask
    restart: unless-stopped