version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs

    depends_on:
      - flask

  flask:
    build: .
    expose:
      - 5001

networks:
  default:
    name: nginx_network
