version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      -  C:/Certbot/live/server.polymathlearning.app/:/etc/nginx/certs
    depends_on:
      - flask

  flask:
    build: .
    expose:
      - 5001

networks:
  default:
    external:
      name: nginx_network
